# Regenerates test/static/ivar_census.txt: for every instance variable the mod reads off a game object,
# which games' scripts actually contain that name.
#
# NOT a spec (no _spec suffix, so the runner ignores it): it reads the decompiled script dumps, which live
# OUTSIDE the repo and are absent on CI. That is why the answer is a committed file rather than a live scan
# -- a check that quietly disappears when its input is missing is exactly the hole this closes.
#
# Run by hand after adding a reader, a profile or a refreshed dump:
#   ruby test/static/build_reader_census.rb ["path\to\decompiled Scripts"]
#
# To get a dump of a game you have, use tools/dump_scripts.rb.
require File.expand_path("reader_sites", File.dirname(__FILE__))

DEFAULT_DUMPS = File.expand_path("../../../../decompiled Scripts", File.dirname(__FILE__))
OUT = File.join(File.dirname(__FILE__), "ivar_census.txt")

dumps = ARGV[0] || ENV["PA_DUMPS"] || DEFAULT_DUMPS
unless File.directory?(dumps)
  puts "dumps folder not found: #{dumps}"
  puts "usage: ruby test/static/build_reader_census.rb [path-to-decompiled-Scripts]"
  exit 1
end

games = Dir.glob(File.join(dumps, "*")).select { |d| File.directory?(d) }.map { |d| File.basename(d) }.sort
if games.empty?
  puts "no game folders under #{dumps}"
  exit 1
end

wanted = {}
ReaderSites.ivars_by_file.each_value { |names| names.each { |n| wanted[n] = {} } }

# One pass per game over its whole dump, matching every wanted name at once: the dumps are tens of
# megabytes and a pass per name would be hundreds of passes over the same bytes. Read binary, because the
# dumps carry Latin-1 accents in comments and a UTF-8 String would raise on the match.
#
# The owning class is tracked alongside, because "which game has this name" is only half the question a
# reader needs answered: a name can be present in the game and still be on the wrong OBJECT, which is a
# silent nil just the same. The check cannot decide that on its own -- it would have to know which object
# each read is aimed at -- so the census names the classes instead, and the answer is one grep away rather
# than an afternoon in the dumps.
names = wanted.keys.sort
owners = {}
pattern = /@(#{names.map { |n| Regexp.escape(n) }.join("|")})\b/
games.each do |g|
  profile = ReaderSites::PROFILE_OF[g] || g
  Dir.glob(File.join(dumps, g, "**", "*.rb")).each do |f|
    cur = nil
    cur_indent = nil
    File.open(f, "rb") do |io|
      io.each_line do |line|
        if line =~ /^(\s*)(?:class|module)\s+([A-Z][A-Za-z0-9_:]*)/
          cur_indent = $1.length
          cur = $2.split("::").last
        end
        line.scan(pattern) do
          wanted[$1][profile] = true
          (owners[$1] ||= {})[cur] = true if cur
        end
      end
    end
  end
end

File.open(OUT, "wb") do |io|
  io.print("# GENERATED by test/static/build_reader_census.rb -- do not edit by hand.\n")
  io.print("#\n")
  io.print("# For each instance variable the mod reads off a game object, the profiles whose game actually\n")
  io.print("# has that name anywhere in its scripts. An empty list means NO surveyed game has it, which is\n")
  io.print("# the silent-nil bug this exists to catch: the hook binds, the read answers nil forever.\n")
  io.print("#\n")
  io.print("# format: @name = <profile>, <profile>...  |  <class that has it>, ...\n")
  io.print("# The class list is informational -- the check reads only the profiles before the bar. It is\n")
  io.print("# there because a name can be present in the game and still sit on the WRONG OBJECT, which is a\n")
  io.print("# silent nil just the same, and this turns finding out into one grep.\n")
  io.print("# surveyed profiles (#{games.length}): #{games.map { |g| ReaderSites::PROFILE_OF[g] || g }.sort.join(', ')}\n")
  io.print("# names read: #{names.length} / never found: #{wanted.values.count { |h| h.empty? }}\n")
  names.each do |n|
    klasses = (owners[n] || {}).keys.sort
    shown = (klasses.length > 8) ? klasses[0, 8] + ["+#{klasses.length - 8} more"] : klasses
    io.print("@#{n} = #{wanted[n].keys.sort.join(', ')}#{klasses.empty? ? '' : '  |  ' + shown.join(', ')}\n")
  end
end

puts "wrote #{OUT}: #{names.length} ivar names across #{games.length} games"
missing = names.select { |n| wanted[n].empty? }
puts "never found in any dump (#{missing.length}): #{missing.join(', ')}" unless missing.empty?

# --- second census: which of the methods the mod binds an AFTER hook to are the screen's blocking loop.
#
# An after hook runs when its method RETURNS. Bound to the loop that IS the screen, it fires on the way out,
# so the screen is silent for exactly as long as the player is in it -- and the reader looks perfectly
# correct, because it is: it is just being asked at the only moment nobody is listening.
#
# A method blocks when it both loops and pumps the frame: a loop alone is any bit of data processing, and
# Graphics.update inside one is what makes it the screen's own turn-taking. One level of indirection counts
# too, because the common shape is a constructor whose last statement is the loop method.
LOOP_OUT = File.join(File.dirname(__FILE__), "loop_census.txt")
LOOP_FORM = /^\s*(?:loop\s+do|while\s+true|until\s+false)\b/
PUMP_FORM = /\bGraphics\.update\b/

hooked = {}
ReaderSites.after_hooks_by_file.each_value { |sites| sites.each { |s| hooked[s] = {} } }
hooked_classes = {}
hooked.each_key { |s| hooked_classes[s.split("#").first.split("::").last] = true }

games.each do |g|
  profile = ReaderSites::PROFILE_OF[g] || g
  direct = {}
  calls = {}
  Dir.glob(File.join(dumps, g, "**", "*.rb")).each do |f|
    cur = nil
    lines = File.open(f, "rb") { |io| io.readlines }
    lines.each_with_index do |line, i|
      if line =~ /^\s*(?:class|module)\s+([A-Z][A-Za-z0-9_:]*)/
        cur = $1.split("::").last
        next
      end
      next unless cur && hooked_classes[cur]
      next unless line =~ /^(\s*)def\s+(?:self\.)?([a-zA-Z_]\w*[?!]?)/
      indent = $1.length
      meth = $2
      body = []
      j = i + 1
      while j < lines.length
        break if lines[j] =~ /^\s{#{indent}}end\b/ && lines[j][/^\s*/].length == indent
        body.push(lines[j])
        j += 1
      end
      text = body.join
      key = "#{cur}##{meth}"
      direct[key] = true if text =~ LOOP_FORM && text =~ PUMP_FORM
      # Indirection counts only when the call is the method's LAST statement. That is the shape that matters
      # -- a constructor whose final act is to run the screen -- and stopping there is what keeps a method
      # that merely CAN reach a blocking animation down one branch from being called a blocking loop.
      tail = body.reverse.find { |l| l.strip != "" && l.strip != "end" }
      calls[key] = (tail.to_s =~ /^\s*(?:self\.)?([a-z_]\w*)\s*$/) ? ["#{cur}##{$1}"] : []
    end
  end
  hooked.each_key do |key|
    next unless direct[key] || (calls[key] || []).any? { |c| direct[c] }
    hooked[key][profile] = true
  end
end

File.open(LOOP_OUT, "wb") do |io|
  io.print("# GENERATED by test/static/build_reader_census.rb -- do not edit by hand.\n")
  io.print("#\n")
  io.print("# For each Class#method the mod binds an AFTER hook to, the profiles whose copy of that method is\n")
  io.print("# the screen's own blocking loop -- it loops and pumps Graphics.update, directly or through one\n")
  io.print("# call. An after hook on one of those runs when the player LEAVES the screen, so the reader is\n")
  io.print("# silent the whole time it is open. A non-empty list is the bug; the answer is around + a poll.\n")
  io.print("#\n")
  io.print("# format: Class#method = <profile>, <profile>...\n")
  io.print("# after-style hook sites: #{hooked.length} / blocking somewhere: #{hooked.values.count { |h| !h.empty? }}\n")
  hooked.keys.sort.each { |k| io.print("#{k} = #{hooked[k].keys.sort.join(', ')}\n") }
end

blocking = hooked.keys.sort.select { |k| !hooked[k].empty? }
puts "wrote #{LOOP_OUT}: #{hooked.length} after-hook sites, #{blocking.length} blocking"
puts "blocking: #{blocking.join(', ')}" unless blocking.empty?
