# Builds test/static/era_census.txt: every pb-prefixed Essentials name shared core (core/ minus gen6/, v21/, v22/)
# calls, and which sources define it, from the decompiled dumps (absent on CI). Names in strings, the mod's own and
# wrapper aliases are dropped. Run: ruby test/static/build_era_census.rb ["path\to\decompiled Scripts"]
require "find"

DEFAULT_DUMPS = File.expand_path("../../../../decompiled Scripts", File.dirname(__FILE__))
ROOT = File.expand_path("../..", File.dirname(__FILE__))
OUT = File.join(File.dirname(__FILE__), "era_census.txt")
VANILLA = File.expand_path("../../../../pokemon-essentials/Data/Scripts", File.dirname(__FILE__))
ERA_DIR = %r{/(gen6|v21|v22)/}
CALL = /(?<![A-Za-z0-9_:@$])\.?(pb[A-Z][A-Za-z0-9_]*[?!]?)/
DEF = /^\s*def\s+(?:[A-Za-z_][\w:]*\.)?(pb[A-Z][A-Za-z0-9_]*[?!]?)/

dumps = ARGV[0] || ENV["PA_DUMPS"] || DEFAULT_DUMPS
unless File.directory?(dumps)
  puts "usage: ruby test/static/build_era_census.rb [path-to-decompiled-Scripts]"
  puts "not a directory: #{dumps}"
  exit 1
end

own = {}
calls = {}
note = lambda do |name, rel|
  next if name.include?("__")
  (calls[name] ||= []).push(rel) unless (calls[name] || []).include?(rel)
end
# A quoted name counts as a call when wrap_kernel, wrap_global or kernel( appears on its line or the next three (a
# loop's name list sits just above its wrap), so a hook label or window key is not taken for a function.
Dir.glob(File.join(ROOT, "core", "**", "*.rb")).sort.each do |f|
  rel = f[ROOT.length + 1..-1].tr("\\", "/")
  src = File.read(f)
  src.scan(DEF) { |(name)| own[name] = true }
  next if rel =~ ERA_DIR
  lines = src.lines.to_a
  lines.each_with_index do |ln, i|
    next if ln =~ /\A\s*#/
    bare = ln.sub(/\s#(?!\{).*\z/, "")
    near = lines[i, 4].join
    bare.scan(/"(pb[A-Z][A-Za-z0-9_]*[?!]?)"/) { |(name)| note.call(name, rel) } if near =~ /\b(?:wrap_kernel|wrap_global|kernel)\(/
    code = bare.gsub(/"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'/, '""')
    code.scan(CALL) { |(name)| note.call(name, rel) }
  end
end
own.keys.each { |name| calls.delete(name) }

sources = {}
Dir.entries(dumps).sort.each do |g|
  next if g.start_with?(".", "_")
  path = File.join(dumps, g)
  sources[g] = path if File.directory?(path)
end
vanilla = ENV["PA_VANILLA"] || VANILLA
if File.directory?(vanilla)
  sources["vanilla"] = vanilla
else
  puts "note: vanilla Essentials tree not found at #{vanilla}"
end

defined_in = {}
sources.keys.sort.each do |g|
  Find.find(sources[g]) do |f|
    next unless f =~ /\.rb\z/i
    src = (File.open(f, "rb") { |h| h.read } rescue nil)
    next if src.nil?
    src.scan(DEF) { |(name)| (defined_in[name] ||= {})[g] = true if calls.has_key?(name) }
    src.scan(/\b(?:alias|alias_method)\s+:?(pb[A-Z][A-Za-z0-9_]*[?!]?)/) { |(name)| (defined_in[name] ||= {})[g] = true if calls.has_key?(name) }
    src.scan(/define_method\(\s*:(pb[A-Z][A-Za-z0-9_]*[?!]?)/) { |(name)| (defined_in[name] ||= {})[g] = true if calls.has_key?(name) }
  end
end

games = sources.keys.sort
partial = calls.keys.sort.select { |name| (defined_in[name] || {}).length < games.length }
File.open(OUT, "w") do |f|
  f.write("# GENERATED by test/static/build_era_census.rb -- do not edit by hand.\n")
  f.write("#\n")
  f.write("# Essentials API names (pb*) called from SHARED core that not every surveyed source defines, so a\n")
  f.write("# call to one has to be a ladder, a guard, or an explained entry in era_calls_spec.rb.\n")
  f.write("# format: <name> = <sources defining it>/<sources>;<sources missing it>;<calling files>\n")
  f.write("# surveyed sources (#{games.length}): #{games.join(', ')}\n")
  f.write("# names called from shared core: #{calls.length} / defined everywhere: #{calls.length - partial.length}\n")
  partial.each do |name|
    have = defined_in[name] || {}
    missing = games.reject { |g| have[g] }
    f.write("#{name} = #{have.length}/#{games.length};#{missing.join(',')};#{calls[name].join(',')}\n")
  end
end
puts "wrote #{OUT}: #{partial.length} of #{calls.length} shared-core API names are not defined by every source (#{games.length} sources)"
