# Builds test/static/era_census.txt: every Essentials API name (the pb-prefixed functions and methods) that
# the SHARED core calls, and which surveyed sources define it. Run it the way the other census builders are
# run -- it reads the decompiled dumps, which live OUTSIDE the repo and are absent on CI:
#
#   ruby test/static/build_era_census.rb ["path\to\decompiled Scripts"]
#
# Why this census exists. Shared core runs on both engine eras, and it asks the game for things under
# `rescue`, so a call to a method only ONE era defines does not fail: it answers nil in the other era, for
# ever, and the reader built on it is silent there without a trace. The spin-tile reader asked
# $game_player.pbTerrainTag, a modern method, and the two games with spin tiles are gen-6: it never named a
# direction in any game. The names below are the mechanical half of that class -- the API names Essentials
# spells with its pb prefix -- so a call to one that some game lacks has to be either a ladder to the other
# era's name, a guard, or an entry in era_calls_spec.rb with its reason.
#
# Shared core is core/ minus the era folders (gen6/, v21/, v22/), whose files are gated by construction.
# Names inside string literals are dropped (they are hook labels and window keys), names the mod defines
# itself are dropped, and so are the wrapper aliases (__pa_ / __access_ suffixes).
require "find"

DEFAULT_DUMPS = File.expand_path("../../../../decompiled Scripts", File.dirname(__FILE__))
ROOT = File.expand_path("../..", File.dirname(__FILE__))
OUT = File.join(File.dirname(__FILE__), "era_census.txt")
VANILLA = File.expand_path("../../../../pokemon-essentials/Data/Scripts", File.dirname(__FILE__))
ERA_DIR = %r{/(gen6|v21|v22)/}
CALL = /(?<![A-Za-z0-9_:@$])\.?(pb[A-Z][A-Za-z0-9_]*[?!]?)/
DEF = /^\s*def\s+(?:[A-Za-z_][\w:]*\.)?(pb[A-Z][A-Za-z0-9_]*[?!]?)/

dumps = ARGV[0] || ENV["PA_DUMPS"] || DEFAULT_DUMPS
unless File.directory?(dumps)
  puts "usage: ruby test/static/build_era_census.rb [path-to-decompiled-Scripts]"
  puts "not a directory: #{dumps}"
  exit 1
end

own = {}
calls = {}
note = lambda do |name, rel|
  next if name.include?("__")
  (calls[name] ||= []).push(rel) unless (calls[name] || []).include?(rel)
end
Dir.glob(File.join(ROOT, "core", "**", "*.rb")).sort.each do |f|
  rel = f[ROOT.length + 1..-1].tr("\\", "/")
  src = File.read(f)
  src.scan(DEF) { |(name)| own[name] = true }
  next if rel =~ ERA_DIR
  lines = src.lines.to_a
  lines.each_with_index do |ln, i|
    next if ln =~ /\A\s*#/
    bare = ln.sub(/\s#(?!\{).*\z/, "")
    # A function wrapped BY NAME is a call to it too: wrap_kernel("pbShowCommandsRogue") binds one game's
    # function and quietly none of the others', which is exactly what the census is for. Only where a wrap
    # follows within a few lines (the name list of a loop sits just above its wrap_kernel), so a hook label
    # or a window key in quotes is not taken for a function.
    near = lines[i, 4].join
    bare.scan(/"(pb[A-Z][A-Za-z0-9_]*[?!]?)"/) { |(name)| note.call(name, rel) } if near =~ /\b(?:wrap_kernel|wrap_global|kernel)\(/
    code = bare.gsub(/"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'/, '""')
    code.scan(CALL) { |(name)| note.call(name, rel) }
  end
end
own.keys.each { |name| calls.delete(name) }

sources = {}
Dir.entries(dumps).sort.each do |g|
  next if g.start_with?(".", "_")
  path = File.join(dumps, g)
  sources[g] = path if File.directory?(path)
end
vanilla = ENV["PA_VANILLA"] || VANILLA
if File.directory?(vanilla)
  sources["vanilla"] = vanilla
else
  puts "note: vanilla Essentials tree not found at #{vanilla}"
end

defined_in = {}
sources.keys.sort.each do |g|
  Find.find(sources[g]) do |f|
    next unless f =~ /\.rb\z/i
    src = (File.open(f, "rb") { |h| h.read } rescue nil)
    next if src.nil?
    src.scan(DEF) { |(name)| (defined_in[name] ||= {})[g] = true if calls.has_key?(name) }
    src.scan(/\b(?:alias|alias_method)\s+:?(pb[A-Z][A-Za-z0-9_]*[?!]?)/) { |(name)| (defined_in[name] ||= {})[g] = true if calls.has_key?(name) }
    src.scan(/define_method\(\s*:(pb[A-Z][A-Za-z0-9_]*[?!]?)/) { |(name)| (defined_in[name] ||= {})[g] = true if calls.has_key?(name) }
  end
end

games = sources.keys.sort
partial = calls.keys.sort.select { |name| (defined_in[name] || {}).length < games.length }
File.open(OUT, "w") do |f|
  f.write("# GENERATED by test/static/build_era_census.rb -- do not edit by hand.\n")
  f.write("#\n")
  f.write("# Essentials API names (pb*) called from SHARED core that not every surveyed source defines, so a\n")
  f.write("# call to one has to be a ladder, a guard, or an explained entry in era_calls_spec.rb.\n")
  f.write("# format: <name> = <sources defining it>/<sources>;<sources missing it>;<calling files>\n")
  f.write("# surveyed sources (#{games.length}): #{games.join(', ')}\n")
  f.write("# names called from shared core: #{calls.length} / defined everywhere: #{calls.length - partial.length}\n")
  partial.each do |name|
    have = defined_in[name] || {}
    missing = games.reject { |g| have[g] }
    f.write("#{name} = #{have.length}/#{games.length};#{missing.join(',')};#{calls[name].join(',')}\n")
  end
end
puts "wrote #{OUT}: #{partial.length} of #{calls.length} shared-core API names are not defined by every source (#{games.length} sources)"
