# Regenerates test/static/ivar_census.txt: for every instance variable the mod reads off a game object,
# which games' scripts actually contain that name.
#
# NOT a spec (no _spec suffix, so the runner ignores it): it reads the decompiled script dumps, which live
# OUTSIDE the repo and are absent on CI. That is why the answer is a committed file rather than a live scan
# -- a check that quietly disappears when its input is missing is exactly the hole this closes.
#
# Run by hand after adding a reader, a profile or a refreshed dump:
#   ruby test/static/build_reader_census.rb ["path\to\decompiled Scripts"]
#
# To get a dump of a game you have, use tools/dump_scripts.rb.
require File.expand_path("reader_sites", File.dirname(__FILE__))

DEFAULT_DUMPS = File.expand_path("../../../../decompiled Scripts", File.dirname(__FILE__))
OUT = File.join(File.dirname(__FILE__), "ivar_census.txt")

dumps = ARGV[0] || ENV["PA_DUMPS"] || DEFAULT_DUMPS
unless File.directory?(dumps)
  puts "dumps folder not found: #{dumps}"
  puts "usage: ruby test/static/build_reader_census.rb [path-to-decompiled-Scripts]"
  exit 1
end

games = Dir.glob(File.join(dumps, "*")).select { |d| File.directory?(d) }.map { |d| File.basename(d) }.sort
if games.empty?
  puts "no game folders under #{dumps}"
  exit 1
end

# Vanilla Essentials joins the survey as a fourteenth source. No fangame here runs v22, so every v22 reader
# was unverifiable by construction: its classes, methods and ivars appeared in no dump and the checks had to
# exempt the whole folder. The upstream tree is a plain script folder like any other, so pointing the same
# scan at it answers those reads against the engine they were written for -- and answers the v21 ones twice.
VANILLA = File.expand_path("../../../../pokemon-essentials/Data/Scripts", File.dirname(__FILE__))
vanilla = ENV["PA_VANILLA"] || VANILLA
sources_of = {}
games.each { |g| sources_of[g] = File.join(dumps, g) }
if File.directory?(vanilla)
  games.push("vanilla")
  sources_of["vanilla"] = vanilla
  games = games.sort
else
  puts "note: vanilla Essentials tree not found at #{vanilla} -- v22 readers stay unverifiable"
end

wanted = {}
ReaderSites.ivars_by_file.each_value { |names| names.each { |n| wanted[n] = {} } }

# One pass per game over its whole dump, matching every wanted name at once: the dumps are tens of
# megabytes and a pass per name would be hundreds of passes over the same bytes. Read binary, because the
# dumps carry Latin-1 accents in comments and a UTF-8 String would raise on the match.
#
# The owning class is tracked alongside, because "which game has this name" is only half the question a
# reader needs answered: a name can be present in the game and still be on the wrong OBJECT, which is a
# silent nil just the same. The check cannot decide that on its own -- it would have to know which object
# each read is aimed at -- so the census names the classes instead, and the answer is one grep away rather
# than a manual search of the dumps.
names = wanted.keys.sort
owners = {}
pattern = /@(#{names.map { |n| Regexp.escape(n) }.join("|")})\b/
games.each do |g|
  profile = ReaderSites::PROFILE_OF[g] || g
  Dir.glob(File.join(sources_of[g], "**", "*.rb")).each do |f|
    stack = ReaderSites::ClassStack.new
    File.open(f, "rb") do |io|
      io.each_line do |line|
        cur = stack.feed(line)
        line.scan(pattern) do
          wanted[$1][profile] = true
          (owners[$1] ||= {})[cur] = true if cur
        end
      end
    end
  end
end

File.open(OUT, "wb") do |io|
  io.print("# GENERATED by test/static/build_reader_census.rb -- do not edit by hand.\n")
  io.print("#\n")
  io.print("# For each instance variable the mod reads off a game object, the profiles whose game actually\n")
  io.print("# has that name anywhere in its scripts. An empty list means NO surveyed game has it, which is\n")
  io.print("# the silent-nil bug this exists to catch: the hook binds, the read answers nil forever.\n")
  io.print("#\n")
  io.print("# format: @name = <profile>, <profile>...  |  <class that has it>, ...\n")
  io.print("# The class list is informational -- the check reads only the profiles before the bar. It is\n")
  io.print("# there because a name can be present in the game and still sit on the WRONG OBJECT, which is a\n")
  io.print("# silent nil just the same, and this turns finding out into one grep.\n")
  io.print("# surveyed profiles (#{games.length}): #{games.map { |g| ReaderSites::PROFILE_OF[g] || g }.sort.join(', ')}\n")
  io.print("# names read: #{names.length} / never found: #{wanted.values.count { |h| h.empty? }}\n")
  names.each do |n|
    klasses = (owners[n] || {}).keys.sort
    shown = (klasses.length > 8) ? klasses[0, 8] + ["+#{klasses.length - 8} more"] : klasses
    io.print("@#{n} = #{wanted[n].keys.sort.join(', ')}#{klasses.empty? ? '' : '  |  ' + shown.join(', ')}\n")
  end
end

puts "wrote #{OUT}: #{names.length} ivar names across #{games.length} games"
missing = names.select { |n| wanted[n].empty? }
puts "never found in any dump (#{missing.length}): #{missing.join(', ')}" unless missing.empty?

# --- second census: which of the methods the mod binds an AFTER hook to are the screen's blocking loop.
#
# An after hook runs when its method RETURNS. Bound to the loop that IS the screen, it fires on the way out,
# so the screen is silent for exactly as long as the player is in it -- and the reader looks perfectly
# correct, because it is: it is just being asked at the only moment nobody is listening.
#
# A method blocks when it both loops and pumps the frame: a loop alone is any bit of data processing, and
# pumping inside one is what makes it the screen's own turn-taking. One level of indirection counts too,
# because the common shape is a constructor whose last statement is the loop method.
#
# All three forms below started too narrow, and the narrowness was invisible: every row came out clean, so
# the file read as thirteen games' worth of evidence when parts of it could not produce a finding at all.
#
# PUMP_FORM was Graphics.update alone. Every Battle::Scene modal loop pumps through pbUpdate or
# pbGraphicsUpdate instead (royal's 002_Battle_Scene), so NO battle-scene loop was
# detectable -- the ability splash, the level-up panels and the battler grid all reported clean.
#
# LOOP_FORM was loop/while true/until false. A plain conditional while is the same screen loop written
# differently, and widening it adds 263 methods across the fourteen sources. `for` is deliberately left
# out: it produced four false positives, all `for i in 0..2` next to an animation.
LOOP_OUT = File.join(File.dirname(__FILE__), "loop_census.txt")
LOOP_FORM = /^\s*(?:loop\s+do|while\b|until\b)/
PUMP_FORM = /\b(?:Graphics\.update|pbUpdate|pbGraphicsUpdate)\b/

hooked = {}
ReaderSites.after_hooks_by_file.each_value { |sites| sites.each { |s| hooked[s] = {} } }
hooked_classes = {}
hooked.each_key { |s| hooked_classes[s.split("#").first.split("::").last] = true }

# The scan below indexes by the LAST namespace segment, because that is the only name a decompiled `class`
# line reliably carries. The census keys are fully qualified, so every lookup has to be shortened the same
# way -- it was not, and all twenty-eight namespaced sites (Battle::Scene, UI::*, VideoPoker::*) missed on
# every game and were reported as clean without a single comparison having been made.
def short_key(key)
  cls, meth = key.split("#", 2)
  "#{cls.split('::').last}##{meth}"
end

# Which sites any dump defines at all. A site nothing defines cannot be checked, and printing it with the
# same empty list as a checked-and-clean one is the difference between "no bug" and "no evidence".
# evidence is keyed by the DEFINING class; seen records the hook keys some game answered for, whether on
# the class itself, an ancestor or Object.
evidence = {}
seen = {}

games.each do |g|
  profile = ReaderSites::PROFILE_OF[g] || g
  direct = {}
  calls = {}
  # The superclass lines first, on their own pass, so the defs pass can keep evidence for the ANCESTORS of a
  # hooked class as well: a hooked method the class inherits -- addLabel on ButtonEventScene comes from
  # EventScene -- is defined where nothing is hooked, and a pass that only kept the hooked classes filed it
  # as NO-DUMP.
  supers = {}
  Dir.glob(File.join(sources_of[g], "**", "*.rb")).each do |f|
    src = File.open(f, "rb") { |io| io.read }
    src.scan(/^\s*class\s+([A-Z][A-Za-z0-9_:]*)\s*<\s*([A-Z][A-Za-z0-9_:]*)/) { |a, b| supers[a.split("::").last] = b.split("::").last }
  end
  wanted = {}
  hooked_classes.each_key do |c|
    cur = c
    6.times do
      wanted[cur] = true
      cur = supers[cur]
      break if cur.nil?
    end
  end
  Dir.glob(File.join(sources_of[g], "**", "*.rb")).each do |f|
    stack = ReaderSites::ClassStack.new
    lines = File.open(f, "rb") { |io| io.readlines }
    lines.each_with_index do |line, i|
      cur = stack.feed(line)
      # attr_accessor and friends define real methods with no body: a hooked getter or setter that comes
      # from one would report NO-DUMP, which reads as "nothing to check" when the truth is "nothing that
      # could ever block". Game_Temp#in_battle= and #in_menu= are both of these.
      if cur && line =~ /^\s*attr_(accessor|reader|writer)\s+(.+)$/
        kind = $1
        $2.scan(/:([a-zA-Z_]\w*)/) do
          evidence["#{cur}##{$1}"] = true unless kind == "writer"
          evidence["#{cur}##{$1}="] = true unless kind == "reader"
        end
      end
      next if line =~ /^\s*(?:class|module)\s+[A-Z]/
      next unless line =~ /^(\s*)def\s+(?:self\.)?([a-zA-Z_]\w*[?!=]?)/
      indent = $1.length
      meth = $2
      # A def at file scope is not lost: Ruby makes it a private instance method of Object, so every class
      # in the game inherits it, and three of the sites the mod hooks are written exactly that way (awakening
      # closes Glosario_Historia and then defines update_cursor at column 0; likewise its EquipScreen and
      # emerald's WonderCardAlbumScene). Filed under Object and resolved through it below, which is what the
      # interpreter does. Reported as NO-DUMP before -- unfalsifiable rather than clean.
      cur = stack.owner_at(indent) || cur
      cur = "Object" if cur.nil? && indent == 0
      next unless cur && (wanted[cur] || cur == "Object")
      # The body ends at its own `end` OR at the next `def`, whichever comes first. The second terminator is
      # what makes this work on decompiled scripts: RPG Maker's editor lets a method sit at column 0 with its
      # closing `end` indented, and matching the `end` alone then ran straight past it -- one such method
      # swallowed the blocking loop of the NEXT one and was reported as a blocker itself. A method with a
      # nested def is truncated early instead, which fails closed: a missed loop, never an invented one.
      body = []
      j = i + 1
      while j < lines.length
        break if lines[j] =~ /^\s*def\s/
        break if lines[j] =~ /^\s{#{indent}}end\b/ && lines[j][/^\s*/].length == indent
        body.push(lines[j])
        j += 1
      end
      text = body.join
      key = "#{cur}##{meth}"
      evidence[key] = true
      direct[key] = true if text =~ LOOP_FORM && text =~ PUMP_FORM
      # Indirection counts only when the call is the method's LAST statement. That is the shape that matters
      # -- a constructor whose final act is to run the screen -- and stopping there is what keeps a method
      # that merely CAN reach a blocking animation down one branch from being called a blocking loop.
      #
      # A trailing if/unless modifier still counts. "pbSelectBattlerInfo if select" IS the last statement,
      # and it is how DBK opens the battler panel from pbUpdateBattlerSelection -- demanding a bare call
      # meant that whole screen was followed nowhere.
      tail = body.reverse.find { |l| l.strip != "" && l.strip != "end" }
      m = tail.to_s.match(/^\s*(?:self\.)?([a-z_]\w*)\s*(?:(?:if|unless)\s+\S.*)?$/)
      calls[key] = m ? ["#{cur}##{m[1]}"] : []
    end
  end
  # Where to look for a method the class itself does not define: up its superclass chain, then Object,
  # which is where a top-level def lands. Both are what the interpreter would do, and both were reported as
  # NO-DUMP before -- unfalsifiable rather than clean. The chain is capped, so a cycle in a dump cannot
  # spin here.
  aliases = lambda do |s|
    cls, meth = s.split("#", 2)
    out = [s]
    5.times do
      cls = supers[cls]
      break if cls.nil? || out.include?("#{cls}##{meth}")
      out.push("#{cls}##{meth}")
    end
    out.push("Object##{meth}")
    out
  end
  hooked.each_key do |key|
    names = aliases.call(short_key(key))
    hooked[key][profile] = true if names.any? { |k| direct[k] || (calls[k] || []).any? { |c| direct[c] } }
    seen[key] = true if names.any? { |k| evidence[k] }
  end
end

no_evidence = hooked.keys.sort.reject { |k| seen[k] }
unresolved = ReaderSites.unresolved_after_sites

File.open(LOOP_OUT, "wb") do |io|
  io.print("# GENERATED by test/static/build_reader_census.rb -- do not edit by hand.\n")
  io.print("#\n")
  io.print("# For each Class#method the mod binds an AFTER hook to, the profiles whose copy of that method is\n")
  io.print("# the screen's own blocking loop -- it loops and pumps Graphics.update, directly or through one\n")
  io.print("# call. An after hook on one of those runs when the player LEAVES the screen, so the reader is\n")
  io.print("# silent the whole time it is open. A non-empty list is the bug; the answer is around + a poll.\n")
  io.print("#\n")
  io.print("#\n")
  io.print("# format: Class#method = <profile>, <profile>...\n")
  io.print("# surveyed sources (#{games.length}): #{games.map { |g| ReaderSites::PROFILE_OF[g] || g }.sort.join(', ')}\n")
  io.print("# A row marked NO-DUMP is one no surveyed game defines: it was not checked and found clean, it\n")
  io.print("# could not be checked at all. The two used to print identically, which made a sixth of the file\n")
  io.print("# read as evidence it was not.\n")
  io.print("# after-style hook sites: #{hooked.length} / blocking somewhere: #{hooked.values.count { |h| !h.empty? }}")
  io.print(" / no dump defines it: #{no_evidence.length}\n")
  io.print("# after-style sites the extractor cannot resolve (computed class or method): #{unresolved.values.flatten.length}\n")
  hooked.keys.sort.each do |k|
    io.print("#{k} = #{no_evidence.include?(k) ? 'NO-DUMP' : hooked[k].keys.sort.join(', ')}\n")
  end
  io.print("\n")
  io.print("# UNRESOLVED: registered with a computed class or method, so the blocking check never saw them.\n")
  unresolved.keys.sort.each do |path|
    unresolved[path].each { |l| io.print("# #{path}: #{l}\n") }
  end
end

blocking = hooked.keys.sort.select { |k| !hooked[k].empty? }
puts "wrote #{LOOP_OUT}: #{hooked.length} after-hook sites, #{blocking.length} blocking, " +
     "#{no_evidence.length} with no dump, #{unresolved.values.flatten.length} unresolved"
puts "blocking: #{blocking.join(', ')}" unless blocking.empty?

# The spec census: every *_spec.rb the runner must discover, committed so run_all can refuse a sweep
# whose glob went quiet (a renamed folder shrinks the suite without failing anything). Needs no dumps,
# so it regenerates on any machine.
SPEC_OUT = File.join(File.dirname(__FILE__), "spec_census.txt")
test_root = File.expand_path(File.join(File.dirname(__FILE__), ".."))
spec_rel = Dir.glob(File.join(test_root, "{unit,behavior,static}", "**", "*_spec.rb"))
              .map { |p| File.expand_path(p)[(test_root.length + 1)..-1].tr("\\", "/") }.sort
File.open(SPEC_OUT, "wb") do |io|
  io.print("# Spec files run_all must discover. Regenerate: ruby test/static/build_reader_census.rb\n")
  spec_rel.each { |r| io.print(r, "\n") }
end
puts "wrote #{SPEC_OUT}: #{spec_rel.length} spec files"

# --- fourth census: the LIFECYCLE each watched information-window scene really has.
#
# InfoWindow.watch binds a scene's open and close by name, and a name no game answers to binds nothing:
# the class is there, the windows are there, and the screen is simply never entered. Nothing said so. The
# mart shipped exactly that way -- declared against the engine's pbStartScene/pbEndScene, which it has
# neither of, because it names both ends after the mode (pbStartBuyScene/pbEndBuyScene and the sell pair)
# in all fifteen games. The suite stayed green because the stub had been given the engine's pair.
#
# So the census answers two things per watched class: which lifecycle methods the GAMES define on it, and
# which ones the MOD declares. The spec then asks the only question with one right answer -- do the two
# sets meet?
#
# The class is rarely a literal: the phone and the dex list are registered through Hooks.variants over
# their spellings, and the mart through Engine.scene_classes, so those lists count as class names too. And
# an :open list may be a constant, which is resolved from wherever the mod defines it.
LIFE_OUT = File.join(File.dirname(__FILE__), "lifecycle_census.txt")
LIFE_RE = /\A(?:pbStart[A-Za-z]*|pbEnd[A-Za-z]*|start|main)\z/
DEFAULT_OPENERS = %w[pbStartScene start]
MOD_ROOT = File.expand_path("../..", File.dirname(__FILE__))

mod_files = %w[core games plugins].map { |d| Dir.glob(File.join(MOD_ROOT, d, "**", "*.rb")) }.flatten.sort
mod_src = {}
mod_files.each { |f| mod_src[f] = File.read(f).gsub(/^\s*#.*/, "") }

# The openers a constant carries, so a call that passes one can be followed: CONST = [:a, :b] gives the
# list itself, CONST = { :open => [:a, :b], ... } gives its :open list.
OPEN_LIST = /:open\s*=>\s*(?:\[([^\]]*)\]|:([a-z_][A-Za-z0-9_]*))/
def symbols_in(text); text.to_s.scan(/(?<!:):([a-z_][A-Za-z0-9_]*)/).flatten; end
const_opens = {}
mod_src.each_value do |src|
  src.scan(/\b([A-Z][A-Z0-9_]+)\s*=\s*\[([^\]]*)\]/) { |name, body| const_opens[name] = symbols_in(body) }
  src.scan(/\b([A-Z][A-Z0-9_]+)\s*=\s*\{([^}]*)\}/) do |name, body|
    m = body.match(OPEN_LIST)
    const_opens[name] = m ? symbols_in(m[1] || ":#{m[2]}") : [] if m
  end
end

# One InfoWindow.watch call at a time, arguments and all (one level of nested parentheses, for .merge(...)):
# the class is its first argument when literal, else the spellings the file lists through variants or
# scene_classes; the openers are the defaults plus whatever the arguments declare or carry in a constant.
WATCH_CALL = /\bInfoWindow\.watch\(((?:[^()]|\([^()]*\))*)\)/m
watched = {}
mod_src.each do |f, src|
  next unless src =~ /\bInfoWindow\.watch\(/
  listed = []
  [/\bvariants\(\s*\[([^\]]*)\]/, /\bscene_classes\(([^)]*)\)/].each do |re|
    src.scan(re) { |m| listed += m[0].scan(/"([A-Z][A-Za-z0-9_:]*)"/).flatten }
  end
  src.scan(WATCH_CALL) do |m|
    args = m[0]
    names = (args =~ /\A\s*"([A-Z][A-Za-z0-9_:]*)"/) ? [$1] : listed
    opens = DEFAULT_OPENERS.dup
    args.scan(OPEN_LIST) { |lst, one| opens += symbols_in(lst || ":#{one}") }
    args.scan(/\b([A-Z][A-Z0-9_]+)\b/) { |c| opens += (const_opens[c[0]] || []) }
    names.uniq.each do |c|
      watched[c] ||= { :declared => [], :games => {} }
      watched[c][:declared] = (watched[c][:declared] + opens).uniq
    end
  end
end

games.each do |g|
  Dir.glob(File.join(sources_of[g], "**", "*.rb")).each do |path|
    src = File.open(path, "rb") { |io| io.read }
    stack = ReaderSites::ClassStack.new
    src.each_line do |line|
      stack.feed(line)
      next unless line =~ /^(\s*)def\s+([a-zA-Z_][A-Za-z0-9_]*)/
      indent = $1.length
      meth = $2
      next unless meth =~ LIFE_RE
      cur = stack.owner_at(indent)
      (watched[cur][:games][meth] ||= {})[g] = true if cur && watched.has_key?(cur)
    end
  end
end

File.open(LIFE_OUT, "wb") do |io|
  io.print("# GENERATED by test/static/build_reader_census.rb -- do not edit by hand.\n")
  io.print("#\n")
  io.print("# Per InfoWindow-watched scene: the lifecycle methods the MOD declares (its :open list plus the\n")
  io.print("# engine defaults) and the ones the surveyed GAMES define on that class. A watch whose two sets\n")
  io.print("# do not meet binds nothing: the screen is never entered and every window on it is dead, with\n")
  io.print("# the class present, the windows present and nothing anywhere to show for it.\n")
  io.print("# format: Class = declared:a|b ; games:a(n),b(n)   -- an empty games list means no source has it\n")
  io.print("# surveyed sources (#{games.length}): #{games.sort.join(', ')}\n")
  watched.keys.sort.each do |c|
    rows = watched[c][:games].keys.sort.map { |m| "#{m}(#{watched[c][:games][m].length})" }
    io.print("#{c} = declared:#{watched[c][:declared].sort.join('|')} ; games:#{rows.join(',')}\n")
  end
end
dead = watched.keys.select { |c| !watched[c][:games].empty? && (watched[c][:declared] & watched[c][:games].keys).empty? }
puts "wrote #{LIFE_OUT}: #{watched.length} watched scenes, #{dead.length} declared against a lifecycle no game has"
puts "sin ciclo de vida: #{dead.join(', ')}" unless dead.empty?
