# Core load order (subsystem/module path, no .rb), evaluated by boot.rb as listed; foundation first.
# core/<module>/ holds the engine-agnostic readers, its subfolders the per-engine parts (gated by class existence):
#   <module>/gen6/     the gen-6 era (Ruby 1.8.7: PokeBattle_Scene, PScreen, PB* data)
#   <module>/v21/      GameData-era Essentials v19-v21.1 (Battle::Scene, GameData, the pre-rework scenes)
#   <module>/v22/      the v22 UI:: rework (UI::BaseScreen / UI::*Visuals)
%w[
  foundation/config
  foundation/const
  foundation/plugins
  foundation/paths
  util/kv_file
  foundation/i18n
  util/grouping
  util/text
  util/player
  foundation/game
  foundation/engine
  foundation/game_lang
  foundation/system_lang
  foundation/settings
  foundation/events
  foundation/caches
  foundation/clipboard
  foundation/perf
  foundation/dictionary
  foundation/tags
  foundation/map_names
  foundation/marks
  data/data
  data/data_fallback
  data/gen6/data_g6
  data/v21/data_v21
  speech/markers
  speech/text
  speech/backend
  speech/categories
  speech/speech
  speech/history
  speech/verbosity
  speech/verbosity_schemes
  input/hooks
  util/paint_capture
  input/keyboard
  input/focus
  input/remap
  input/native_keys
  input/key_hints
  input/input
  input/diag
  menus/config_menu
  menus/config_rows
  menus/config_dicts
  menus/config_verbosity
  menus/config_remap
  nav/terrain
  audio/spatial
  audio/glossary
  audio/audio3d
  field/contextual
  field/hud_text
  field/field_states
  field/minigames
  puzzles/puzzles
  puzzles/stages
  field/location_banner
  field/turbo
  menus/cursor
  menus/menus
  menus/scene_watcher
  menus/menu_return
  menus/neo_pausemenu
  menus/ready_menu
  menus/screen_messages
  menus/modal_panel
  menus/pause_panel
  menus/info_window
  menus/controls_help
  menus/command_help
  menus/sprite_button_menu
  menus/options
  menus/option_help
  menus/number_entry
  menus/text_entry
  field/minigame_text
  menus/appearance
  menus/picture_cues
  menus/load_screen
  menus/title_screen
  menus/gen6/title_screen_g6
  menus/trainer_card
  menus/credits
  menus/v21/trainer_card_v21
  battle/battle
  battle/move_info
  battle/scene_reader
  battle/gen6/battle_g6
  battle/v21/battle_v21
  battle/v22/battle_v22
  battle/pokedex
  menus/pokedex_entry
  battle/v21/pokedex_info_v21
  battle/gen6/pokedex_info_g6
  menus/purify_chamber
  menus/shops
  menus/battle_swap
  menus/marking
  menus/encounter_list
  menus/v21/ui_v21
  menus/pokedex_search/base
  menus/pokedex_search/grid
  menus/pokedex_search/list
  menus/v21/move_relearner_v21
  menus/gen6/move_relearner_g6
  field/hall_of_fame
  field/incubator
  menus/v21/pausemenu_v21
  party/summary_gamedata
  party/v21/summary_v21
  party/v21/ribbons_v21
  menus/move_list
  menus/v22/screen_v22
  menus/v22/options_v22
  menus/v22/bag_v22
  menus/v22/pausemenu_v22
  menus/v22/mart_v22
  menus/v22/move_reminder_v22
  menus/v22/load_save_v22
  menus/v22/trainer_card_v22
  menus/v22/pokegear_v22
  party/v22/party_v22
  party/v22/summary_v22
  party/v22/storage_v22
  battle/v22/pokedex_v22
  nav/v22/town_map_v22
  party/party_storage
  party/gen6/party_g6
  party/v21/party_v21_pause
  menus/load
  menus/save_panel
  field/berry
  nav/locator_naming
  nav/locator_surfaces
  party/summary
  party/gen6/summary_g6
  nav/region_map
  nav/town_map
  nav/locator
  nav/guide
  nav/pathfinder
  nav/route_search
  nav/route_grid
  nav/route_text
  nav/event_pages
  nav/route_events
  nav/route_water
  nav/route_gates
  nav/route_terrain
  nav/field_moves
  nav/map_meta
  dialogue/dialogue
  dialogue/pages
  field/evolution_text
  field/hatch_shiny
  field/mail
  field/fishing
  field/phone
  field/itemfinder
  field/pokeradar
  menus/money_window
  menus/uihelper
  util/recorder
  util/selfcheck
  util/silence
]
