# Infinite Fusion's fusion chooser with what the splicers' screen draws under each fusion: its types, the level the
# fusion will have, and a tinted sprite for a fusion the Pokedex has not seen, each at the Pokemon choice reading's
# level. The screen's class, reduced to the methods the profile hooks, is defined before the file binds to it.
class DoublePreviewScreen
  def initialize(left, right, draw = true)
    @species_left = left
    @species_right = right
    @draw_types = draw
    @draw_level = draw
    @selected = 0
  end
  def drawFusionInformation(_dex_number, _level, _x = 0); nil; end
  def startSelection; @selected; end
  def updateSelectionGraphics; nil; end
  def select(side); @selected = side; updateSelectionGraphics; end
end

load File.expand_path("../../../games/infinitefusion_common/fusion_preview.rb", File.dirname(__FILE__))

# The game's custom sprite test, answered from $if_customs (fusion ids with a custom sprite), shared with the Hoenn
# family spec.
def customSpriteExistsSpecies(species); ($if_customs || []).include?(species); end unless Object.private_method_defined?(:customSpriteExistsSpecies)

module IFFusionPreviewSpec
  Parent = Struct.new(:name)
  Fused = Struct.new(:name, :head_pokemon, :body_pokemon, :type1, :type2, :id_number)

  def self.fused(name, head, body, types, id)
    Fused.new(name, Parent.new(head), Parent.new(body), types[0], types[-1], id)
  end
end

Suite.define("infinite fusion: each fusion says its types and whether it is new, and the level at full") do
  t = PokeAccess::I18n
  old_trainer = $Trainer
  begin
    trainer = Object.new
    def trainer.seen?(id); id == 1; end
    $Trainer = trainer
    left = IFFusionPreviewSpec.fused("Charitoise", "Charizard", "Blastoise", [:FIRE, :WATER], 1)
    right = IFFusionPreviewSpec.fused("Blastizard", "Blastoise", "Charizard", [:WATER, :WATER], 2)
    screen = DoublePreviewScreen.new(left, right)
    screen.drawFusionInformation(1, 45, 20)
    screen.drawFusionInformation(2, 45, 270)

    side = lambda { |sp| t.t(:if_fusion_side, :name => sp.name, :head => sp.head_pokemon.name, :body => sp.body_pokemon.name) }
    SpeakCapture.clear
    screen.startSelection
    eq "the left fusion: head and body, its two types, and the level it will have",
       SpeakCapture.lines, [[side.call(left), t.t(:pdx_type, :t => "TypeFIRE TypeWATER"), t.t(:if_fusion_level, :n => 45)].join(", ")]
    SpeakCapture.clear
    screen.select(1)
    eq "the right one: a single type when both are the same, new to the Pokedex and what its tint means",
       SpeakCapture.lines,
       [[side.call(right), t.t(:pdx_type, :t => "TypeWATER"), t.t(:if_fusion_unseen), t.t(:if_sprite_auto),
         t.t(:if_fusion_level, :n => 45)].join(", ")]

    rows = vb_levels { PokeAccess::IFFusionPreview.describe(right, screen) }
    eq "brief: head and body alone", rows[0], side.call(right)
    eq "medium: its type and that it is new", rows[1], [side.call(right), t.t(:pdx_type, :t => "TypeWATER"), t.t(:if_fusion_unseen)].join(", ")

    plain = DoublePreviewScreen.new(left, right, false)
    plain.drawFusionInformation(1, 30)
    eq "a screen that draws neither types nor level says neither",
       PokeAccess::IFFusionPreview.describe(left, plain), side.call(left)
  ensure
    $Trainer = old_trainer
  end
end

# What the tint over an unseen fusion's sprite means is said at full, by draw_window's own tests: blue, a custom sprite
# already on disk; green, a custom one not downloaded; white, an autogenerated one.
Suite.define("infinite fusion: an unseen fusion's tint is said at full by what it means") do
  t = PokeAccess::I18n
  ui = PokeAccess::IFFusionPreview
  old_trainer = $Trainer
  $if_customs = []
  begin
    trainer = Object.new
    def trainer.seen?(id); id == 1; end
    $Trainer = trainer
    left = IFFusionPreviewSpec.fused("Charitoise", "Charizard", "Blastoise", [:FIRE, :WATER], 1)
    right = IFFusionPreviewSpec.fused("Blastizard", "Blastoise", "Charizard", [:WATER, :WATER], 2)
    screen = DoublePreviewScreen.new(left, right, false)
    eq "white: an autogenerated sprite", ui.tint(screen, right, 1), t.t(:if_sprite_auto)
    $if_customs.push(2)
    eq "green: a custom one not downloaded yet", ui.tint(screen, right, 1), t.t(:if_sprite_custom)
    screen.instance_variable_set(:@sprite_right, Struct.new(:local_path).new("Graphics/CustomBattlers/2.png"))
    eq "blue: one already on disk", ui.tint(screen, right, 1), t.t(:if_sprite_local)
    eq "a seen fusion is not tinted", ui.tint(screen, left, 0), nil
    rows = vb_levels { ui.describe(right, screen, 1) }
    falsy "medium leaves it out", rows[1].include?(t.t(:if_sprite_local))
    truthy "full says it after the unseen mark", rows[2].include?("#{t.t(:if_fusion_unseen)}, #{t.t(:if_sprite_local)}")
    SpeakCapture.clear
    screen.select(1)
    truthy "and so does the arrow moving onto it", SpeakCapture.last.to_s.include?(t.t(:if_sprite_local))
  ensure
    $Trainer = old_trainer
    $if_customs = nil
  end
end
