# Load order for the royal game modules (no .rb), loaded after core. Edit to add/reorder.
%w[
  constants
  selectors
  currydex
  curry_select
  menu_parrilla
  gacha
  tarjetas_liga
  tarjeta_entrenador
  language
  mep_exp
  curry_result
  berrydex
  iconos_leyenda
  puntos
  album_fotos
  hall_viewer
  granja
  decorating
  rhythm
]
