# The Tables of Truth (TablesScreen): two shrines of 16 stone tables each, every one a fullscreen PNG of
# historical commentary -- the game separating its Punic-Wars fiction from the real record. showImage
# blocks on an image with no text, so each table is TRANSCRIBED here off its own PNG, keyed by the
# basename the screen resolves at runtime (@pictures[select]): the "tabla"/"tablo" prefix comes through
# the game's _INTL, so the English mode lands on the _eng transcriptions with no language logic of ours.
# Texts are verbatim from the images, the game's own typos included -- reading, not editing.
module PokeAccess
  module AfricanusTablas
    TEXTS = {
      "tabla1" => "Sagunto - Sucesos en el año 218 a.C. El asedio de Sagunto por parte de Aníbal rompiendo el tratado del Ebro fue un hecho, sin embargo tanto el personaje protagonista como el personaje de Cepressus son inventados para la trama del juego. Aníbal no sufrió una derrota en este asedio, pero sí se dice que fue herido por una jabalina en la pierna durante el mismo. Este asedio comenzaría la segunda guerra púnica.",
      "tabla2" => "Emporiae - Sucesos en el año 218 a.C. Los eventos de Emporiae son ficción histórica, para esa época Publio y Cneo estarían en el norte de Italia, y Publio hijo estaría probablemente formándose en Roma con su hermano y su madre Pomponia. Se hace mención a que Publio planea interceptar a Aníbal en el Ródano, esa tarea sí la trató de llevar a cabo, sin embargo, como se refleja en el juego más tarde, falló en realizarla.",
      "tabla3" => "Massilia - Sucesos en el año 218 a.C. La trama de la captura en la ruta tres es inventada para el juego, aunque sí eran frecuentes los asaltos galos espontáneos por los bosques de aquella época. Al llegar a la polis encontramos un levantamiento griego que nunca ocurrió, pero se usa para ejemplificar que el legado de Alejandro Magno y sus sucesores estaba muy presente las mentes de los griegos del Mediterráneo.",
      "tabla4" => "Pisae - Sucesos en el año 217 a.C. El cruce de los Alpes en el 218 a.C. y la promesa de Aníbal son reales, así como la existencia de Cayo Lelio. Pero su presencia en la ciudad, y su misión de envenenar a Aníbal son ficción, al igual que el personaje de Anaid. Son mencionadas las batallas de Tesino y Trebia, las cuales ocurrieron. El origen humilde de Lelio y su amistad con Publio desde la niñez son reales también.",
      "tabla5" => "Roma - Sucesos en el año ???. Los sucesos de Roma se cubren en las otras tablas a la derecha de esta. Así que sobre la ciudad en sí, cabe recalcar que es una ciudad anacrónica, la Roma presentada en el juego dataría de aproximadamente el 100 d.C. cuando la ciudad estaba en su esplendor. Esto se ha hecho para adecuarse al sentimiento de \"Gran capital\" de la región. ¡Y no se podía dejar a Roma sin coliseo!",
      "tabla6" => "Tarraco - Sucesos en el año 211-210 a.C. Emilia Tercia fue ciertamente, esposa de Publio. Su afición por las joyas es desconocida, aunque era algo común en las damas romanas. Su hija menor con Escipión: Cornelia, madre de los Gracos, sería conocida como modelo de mujer y matrona romana virtuosa. El entrenamiento de Publio refleja el estacionamiento de tropas en sus cuarteles de invierno preparando campañas.",
      "tabla7" => "Cartago Nova - Sucesos en el año 209 a.C. La captura de Cartago Nova suele ser de las mayores gestas de Escipión, esta según Livio, se completó efectivamente en un solo día. Sin embargo, la presencia de Asdrúbal Barca en la ciudad es falsa, en la trama se \"escapa\" para poder continuar su papel en Baecula y Metauro. La clemencia de Escipión con una princesa íbera es un hecho plasmado en el juego, su contención en el saqueo fue sonada.",
      "tabla8" => "Ibossim - Sucesos en el año 205 a.C. La trama de Asherah y Magón es parcialmente histórica. La mujer, los gladiadores y la treta fueron inventadas, pero es cierto que Magón Barca se refugió en Baleares tras la derrota en Ilipa, la cual le dolió más que la de Cartago Nova. Por otro lado, se representa a los turdetanos, un pueblo íbero muy desarollado cuyo final es incierto, pero probablemente ligado al auge cartaginés en la Bética.",
      "tabla9" => "Gades - Sucesos en el año 206 a.C. La cantera es inventada, al igual que la reconstrucción de murallas basada en el Asedio de Constantinopla de 1453. Lucio no fue el artífice del sitio, sino Publio. Y no hubo un saqueo tan brutal, la personalidad del hermano menor de los escipiones es inventada y exagerada para la trama del juego. La Unión de Amat igualmente es pura invención del juego para fines de historia y argumento.",
      "tabla10" => "Carales - Sucesos en el año ??? a.C. Carales no tiene trama, pero en Corsica se presenta a Vulsón Longo, un general real de la primera guerra púnica. Que efectivamente, codirigió la batalla del cabo Ecnomo, pero quedó relegado a un segundo plano frente a Régulo en la historia. El asunto en Sicilia hace referencia a que según la mitología, en esta isla habitaban los cíclopes. Se da a entender que es padre de Lelio, pero es pura invención.",
      "tabla11" => "Tarento - Sucesos en el año 209 a.C. Es importante resaltar el desorden temporal respecto a la conquista de Hispania, la cual ocurrió después y no antes del asedio. La estrategia de Fabio y su papel como augur son fieles a la historia, así como la mención a la batalla del Metauro y decapitación de Asdrúbal. Pero tanto la excavación de túneles y la leyenda de Olympeus son, obviamente, invenciones del juego.",
      "tabla12" => "Siracusa - Sucesos en el año 205 a.C. Plauto posiblemente actuó en el teatro de la polis, pero no en esta época con \"Anfitrión\". Se desconoce la mayoría de su biografía. Emilia no estaba presente, posiblemente estuviera en Roma, y los sucesos del Etna son invención relacionada con la Unión. Olympeus sin embargo, habla del saqueo de Roma del 387 a.C. este hecho mezcla mitología e historia pero es relatado por autores como Plutarco.",
      "tabla13" => "Siga - Sucesos en el año 204 a.C. El desembarco en África se dio prácticamente en Útica, por lo que toda esta trama es inventada, pero nos ayuda a comprender el conflicto númida y revela la alianza matrimonial de Sífax y Giscón. La ciudad no participó en el conflicto y fue anexionada al reino de Masinisa tras la victoria sobre su rival. Mientras, como se dice en el juego, Escipión y Lelio sitiaron Útica temporalmente.",
      "tabla14" => "Iol - Sucesos en el año 203 a.C. El tratado firmado tras la batalla de los grandes campos no fue en esta ciudad, la cual no tuvo relevancia en la guerra, pero este acuerdo formal de paz sí existió con las condiciones relatadas, sin emabargo fue roto cuando Aníbal regresó a África destruyendo una flota romana amarrada a la costa. Se presenta además el líder cartaginés Hanón el grande, enemigo político de Aníbal Barca.",
      "tabla15" => "Cirta - Sucesos en el año 202 a.C. La trama relacionada con el Rapidash es una invención que referencia la guerra de Troya y a Helena, simbolizando a Sofonisba y el papel decisivo de su matrimonio en la guerra. Su actitud se basa en las \"femme fattale\" y su envenamiento ocurrió, pero fue por orden de Roma. Como se muestra en el juego, Masinisa no volvió a tener la misma actitud hacia Roma tras este acontecimiento.",
      "tabla16" => "Cartago - Sucesos en el año 195 a.C. Tras la batalla de Zama, se llega a Cartago no sin antes pasar por Útica (trama inventada). El argumento en esta ciudad es en parte histórico: Cartago hará sufete a Aníbal tras perder la guerra, pero a causa de sus rencillas políticas internas, el Bárcida será entregado a Roma como aparece en el juego. Sin embargo, escapó al Imperio seleúcida, donde pasará sus últimos años como general, muriendo en Bitinia.",
      "tablo1" => "Roma uno - Sucesos en el año 217-216 a.C. Como se muestra en el juego, Fabio asumió la dictadura durante seis meses para solventar la crisis, llevando una política de no-enfrentamiento. La trama de la boda es en realidad una referencia a \"Roma\" de HBO, por lo que es inventada. Pero Escipión probablemente sí se casó durante estos años, y más importantemente, al concluir la dictadura se reunió el ejército de Cannae.",
      "tablo2" => "Publio Cornelio Escipión \"El Africano\". Es el personaje principal y rival, en un inicio iba a ser el protagonista controlable. Publio es uno de los primeros héroes romanos que sacó a Roma de uno de sus peores momentos revertiendo el curso de la guerra y venciendo a uno de los mayores generales de la Historia. Sin embargo, acabó sus días exiliado en Liternum traicionado por su patria, despreciando a Roma en su epitafio.",
      "tablo3" => "Roma dos - Sucesos en el año 210 a.C. Se lleva a cabo un retroceso en el tiempo de cuatro años respecto a Gades para poder observar la campaña completa. Esto nos permite ver el cargo de Augur que ostentaba Fabio, algo verídico, aunque la comunicación con los dioses sobra decir que es inventada. El barrio desbloqueado contiene la zona del Panteón y la Subura, los barrios más bajos. Realmente estos barrios están más alejados entre sí.",
      "tablo4" => "Aníbal Barca. Probablemente el general más famoso de su época, causó un atroz terror en una Roma cuando esta empezaba a despuntar, pudiendo haber acabado con uno de las civilizaciones más relevantes de la historia. En el juego se le caracteriza como un hombre sensato y analista que inspira confianza y terror. Su gesta más ilustre es el cruce de los Alpes representado en la ruta cuatro y Cannae.",
      "tablo5" => "Roma tres - Sucesos en el año 204 a.C. Esta trama es totalmente inventada, pero se utiliza para presentar al personaje de Emilio Paulo Macedónico y especialmente, para retratar conceptos clásicos de la romanidad tales como las carreras de cuádrigas o las termas, donde encontramos una referencia a la vida de Brian. También se presenta la villa de los escipiones en Liternum, de gran importancia en la posteridad.",
      "tablo6" => "Cayo Lelio. Este hombre fue el mejor amigo de Publio durante la mayor parte de su vida. En el juego se representa como un ligero mentor con actitud noble a la vez que socarrona. Él contó en ocasiones a Polibio episodios de la vida de Publio, lo que nos permite conocer su historia. Lelio provenía de una clase un poco más humilde pero llegó a ser cónsul en el año 190 a.C. debido a su amistad con Publio.",
      "tablo7" => "Roma cuatro - Sucesos en el año 201 a.C. Obviamente en la realidad no hubo Liga Pokémon, además, toda la trama con Maharbal, la prisión y el inframundo es también propia del juego sin base histórica, pero dentro de la liga se pelea en una naumaquia, un escenario que llegó a ser real en los anfiteatros. Tras la guerra Publio obtuvo un triunfo y no ocurrió mucho más hasta el conflicto con los seleúcidas.",
      "tablo8" => "Olympeus. Este legendario se basa en el águila romana, en Júpiter y en el emblema que aparece en los escudos romanos, no tiene base en la mitología y sirve como una representación del dios supremo de los romanos en versión Pokémon. Interviene en diversos puntos de la trama y lo recubre un pequeño aura de misticismo.",
      "tablo9" => "Sagunto dos - Sucesos en el año 210 a.C. Como dijimos, el personaje de Cepressus es inventado, al igual que la reconstrucción de Sagunto, que no tuvo nada de especial, la aparición de Emilia es propia aunque sí es cierta la reconquista de la plaza y el plan trazado en la tienda, que muestra el precario estado en el que se encontraba Roma y cómo esta tuvo la constante voluntad de seguir recomponiéndose tras cada derrota.",
      "tablo10" => "La unión de Amat. Surge por la necesidad de un grupo villano paralelo a la propia Cartago, son totalmente inventados pero su \"líder\" Hanón el grande sí fue una de las personalidades más influyentes de Cartago durante la guerra. El nombre del culto deriva del de la diosa Anat, una deidad del panteón fenicio diosa de la fertilidad.",
      "tablo11" => "Cannae - Sucesos en el año 216 a.C. Esta batalla es de las más grandes derrotas romanas y en general está históricamente bien representada especialmente en la fase \"estrategica\" al inicio de la misma, también se representa el sacrificio de Emilio Paulo sustituyendo a Cneo Léntulo por Publio, quien protagoniza el episodio de la arenga ante aquellos que deseaban huir, la cual es cierta según nos cuenta el griego Polibio.",
      "tablo12" => "Panteón. En el panteón se desarolla una secundaria centrada en diversas etapas de la historia romana, estas son por lo general bastante históricas, y también sus ciudades se han hecho basándose en el plano real de las mismas. Las tramas de Augusto y Belisario son más libres, por el contrario, el capítulo de Eneas sigue la obra de Virgilio de manera bastante literal.",
      "tablo13" => "Baecula - Sucesos en el año 209 a.C. La batalla de Baecula se representa de manera bastante correcta por la disposición en una colina que se debe escalar, el ejército romano debio asaltar al cartaginés que se encontraba en la cima de la misma. Obviamente la intervención de Olympeus es inventada, y en la realidad Asdrúbal escapó por su cuenta para así volver con su hermano, pero moriría en la batalla del Metauro.",
      "tablo14" => "Olimpo. El olimpo es un lugar divino en la mitología romana, se asemeja al griego, y dentro del juego encontramos a la mayoría de dioses del panteón latino, destacando a Jano y la representación de Zeus (versión DLH) en contraposición a Júpiter. La apariencia del olimpo recuerda también a la que podrían haber tenido los campos elíseos y contrasta con el inframundo, en el que encontramos a Dante.",
      "tablo15" => "Zama - Sucesos en el año 202 a.C. La representación de la batalla es especialmente en su primera fase, muy precisa. La muerte de Cepressus a manos de Anaid es algo propio de la trama y el duelo entre Escipión y Aníbal posiblemente no ocurrió, sin embargo sí se refleja que tras vencer en esta batalla y conquistar África se le comenzó a llamar Escipión el africano, que en latín se traduce como \"Scipio Africanvs\".",
      "tablo16" => "Atlántida. La Atlántida, el mito de Platón es una celebérrima parte del mundo clásico, en esta ciudad encontramos a Alejandro Magno, un héroe macedonio del siglo cuatro a.C. que supuso un antes y un después en la historia del mundo antiguo, siendo ensalzado y convertido en una verdadera leyenda. Su supervivencia es obviamente falseada y la existencia de la Atlántida no ha sido demostrada... todavía...",
      "tabla_eng1" => "Saguntum - Events in the year 218 BC. The siege of Saguntum made by Hannibal's forces was real. However both the main character and Cepressus were invented for the plot of the game. Hannibal did not suffer a defeat in this siege, but it is said that he was wounded by a javelin in the leg during it. This siege would begin the Second Punic War.",
      "tabla_eng2" => "Emporiae - Events in the year 218 BC. The events of Emporiae are historical fiction, at that time Publius and Gnaeus would be in northern Italy, and Publius Jr. would probably be training in Rome with his brother and mother Pomponia. It is mentioned that Publius plans to intercept Hannibal in the Rhone, that was real event seen en the battle of the Rhone, however, as reflected in the game later, he failed to catch Hannibal.",
      "tabla_eng3" => "Massilia - Events in the year 218 BC. The plot of the gauls on Route three is invented for the game, although spontaneous Gallic raids through the forests of that time were frequent. Upon arriving at the polis we find a Greek uprising that never occurred, but is used to exemplify that the legacy of Alexander the Great and his successors was very present in the minds of the Greeks across the Mediterranean.",
      "tabla_eng4" => "Pisae - Events in the year 217 BC. The crossing of the Alps in 218 BC and Hannibal's promise are real, as is the existence of Gaius Laelius. But his presence in the city, and his mission to poison Hannibal, are fiction, same as the character of Anaid. The battles of Ticino and Trebia are mentioned, which occurred in reality. Lelio's humble origins and his friendship with Publio since their early days are real too.",
      "tabla_eng5" => "Rome - Events in the year ???. Rome's plot is written in the other tables to the right of this one. So about the city itself, it should be noted that it is an anachronistic city, the Rome presented in the game would date from approximately 100 AD, when the city was in its splendor. This has been done to fit the \"Big Capital\" feel of the region. And you couldn't leave Rome without a coliseum!",
      "tabla_eng6" => "Tarraco - Events in the year 211-210 BC. Aemilia Tertia was in fact the wife of Publius. Her love for jewelry is unknown, although it was common among Roman ladies. Her youngest daughter with Scipio: Cornelia, mother of the Gracchi, would be known as a model of women and a virtuous Roman matron. Publius's training reflects the stationing of troops in their winter quarters preparing campaigns.",
      "tabla_eng7" => "Carthage Nova - Events in the year 209 BC. The battle of Carthage Nova is usually one of Scipio's greatest feats; according to Livy, it was effectively completed in a single day. However, Hasdrubal Barca's presence in the city is false; in the plot he \"escapes\" in order to continue his role in Baecula and Metauro. Scipio's clemency towards an Iberian princess is a fact reflected in the game, his restraint in the plunder was notable.",
      "tabla_eng8" => "Ibossim - Events in the year 209 BC. Asherah and Mago's plot is partially historical. Asherah, the fighters and the ruse were invented, but it is true that Mago Barca took refuge in the Balearic Islands after the defeat at Ilipa, which hurt him more than that of Cartago Nova. On the other hand, the Turdetans are represented, a highly developed Iberian people whose end is uncertain, but probably caused by Carthage.",
      "tabla_eng9" => "Gades - Events in the year 206 BC. The quarry is invented, as is the reconstruction of walls based on the Siege of Constantinople of 1453. Lucius was not the architect of the siege, but Publius. And there was no such brutal looting, the personality of the younger brother of the Scipio is invented and exaggerated for the plot of the game. The Union of Amat is also a pure invention of the game for story and plot.",
      "tabla_eng10" => "Carales - Events in the year ??? BC. Carales has no plot, but in Corsica Vulso Longus, a real general from the First Punic War, is introduced. And indeed, he co-directed the battle of Cape Ecnomus, but was relegated to the background compared to Regulus in history. The issue in Sicily refers to the fact that according to mythology, the Cyclops lived on this island. It is implied that he is Laelius' father, but this is pure invention.",
      "tabla_eng11" => "Tarentum - Events in the year 209 BC. It is important to highlight the temporal disorder regarding the conquest of Hispania, which occurred after and not before the siege. Fabius's strategy and his role as augur are historically accurated, as is the mention of the battle of Metaurus and the beheading of Hasdrubal. But both the tunneling and the legend of Olympeus are obviously made up for the game.",
      "tabla_eng12" => "Syracuse - Events in the year 205 BC. Plautus possibly acted in the theater of the polis, but not in this age with \"Amphitruo\". The majority of your biography is unknown. Aemilia was not ther neither, she was possibly in Rome, and the events of Etna were not real and related to the Union. However, Olympeus talks about the sacking of Rome dated in 387 BC. This is a mixture of mythology and history but authors like Plutarch mention it.",
      "tabla_eng13" => "Siga - Events in the year 204 BC. The landing in Africa was near Utica, so this whole plot is invented, but it helps us to understand the conflict in Numidia and reveals the marital alliance of Syphax and Gisco. The city did not participate in the conflict and was annexed to Masinisa's kingdom after the victory over his rival. Meanwhile, as they say in the game, Scipio and Laelius besieged Utica at this time.",
      "tabla_eng14" => "Iol - Events in the year 204 BC. The treaty signed after the battle of the great plains was not in this city, which had no relevance in the war, but this formal peace agreement did exist with the conditions described. However it was broken when Hannibal returned to Africa destroying a roman fleet. The Carthaginian leader Hanno the Great, political enemy of Hannibal Barca, was also real.",
      "tabla_eng15" => "Cirta - Events in the year 204 BC. The plot related to the Rapidash is an invention that references the Trojan War and Helen, symbolizing Sophonisba and the decisive role of her marriage in the war. Her attitude is based on the \"femme fatale\" and her poisoning occurred, but it was ordered by Rome. As shown in the game, Masinisa did not have the same attitude towards Rome after this event.",
      "tabla_eng16" => "Cartago - Events in the year 195 BC. After the battle of Zama, you reach Carthage passing through Utica (invented plot). The plot in this city is partly historical: Carthage will submit to Hannibal after losing the war, but because of their internal political quarrels, the general will be handed over to Rome as it appears in the game. However, he escaped to the Seleucid Empire, where he would spend his last years as a general, dying in Bithynia.",
      "tablo_eng1" => "Rome one - Events in the year 217-216 BC. As shown in the game, Fabio assumed the dictatorship for six months to solve the crisis, carrying out a policy of no-fighting. The wedding plot is actually a reference to HBO's \"Rome\", so it's made up. But Scipio probably did marry during these years and more importantly, at the end of the dictatorship the army of Cannae was raised.",
      "tablo_eng2" => "Publius Cornelius Scipio \"Africanus\". He is the main character and rival, initially he was going to be the controllable protagonist. Publius is one of the first Roman heroes who saved Rome from of one of its worst moments by reversing the course of the war and defeating one of the greatest generals in history. However, he ended his days in exile in Liternum, betrayed by his country, despising Rome in his epitaph.",
      "tablo_eng3" => "Rome two - Events in the year 210 BC. A setback in time of four years with respect to Gades to observe the full campaign. This allows us to see Fabius' position of Augur, something true, although the communication with the gods goes without saying that it is invented. The unlocked neighborhood contains the Pantheon area and the Subura, the poorest neighborhoods. These neighborhoods are actually further away from each other.",
      "tablo_eng4" => "Hannibal Barca. Probably the most famous general of his time, he caused atrocious terror in Rome when it was beginning to emerge, and could have ended one of the most important civilizations in history. In the game he is characterized as a sensible and analytical man who inspires confidence and terror. His most illustrious feat is the crossing of the Alps represented on route four and the battle of Cannae.",
      "tablo_eng5" => "Rome three - Events in the year 204 BC. This plot is completely invented, but it is used to present the character of Aemilius Paulus Macedonicus and especially to portray classic Roman concepts such as chariot races or hot springs, where we find a reference to Life of Brian. The villa of the Scipios in Liternum, which will be of great importance in posterity, is also presented.",
      "tablo_eng6" => "Gaius Laelius. This man was Publius's best friend for most of his life. In the game he is represented as a light mentor with a noble yet sly attitude. He sometimes told Polybius episodes from the life of Publius, which allows us to know his story. Laelius came from a slightly more humble class but became consul in 190 BC due to his friendship with Publius.",
      "tablo_eng7" => "Rome four - Events in the year 201 BC. Obviously in reality there was no Pokemon League, in addition, the entire plot with Maharbal, the prison and the underworld is also mad up for the game without a historical basis, but within the league there is a fight in a naumaquia, a scenario that real. In reality, after the war, Publius obtained a triumph and not much else happened until the conflict with the Seleucids.",
      "tablo_eng8" => "Olympeus. This legendary Pokemon is based on the Roman eagle, Jupiter and the emblem that appears on Roman shields. It has no basis in mythology and serves as a representation of the supreme god of the Romans in a Pokemon version. He intervenes at various points in the plot and is covered with a small aura of mysticism.",
      "tablo_eng9" => "Saguntum two - Events in the year 210 BC. As we said, the character of Cepressus is invented, as is the reconstruction of Saguntum, which had nothing special, the presence of Aemilia is also invented, although the reconquest of the city and the plan drawn up in the tent are true, which shows the precarious state in which Rome found itself and how it had the constant will to continue rebuilding itself after each defeat.",
      "tablo_eng10" => "The union de Amat. It comes from the need for a evil group parallel to Carthage itself, they are completely invented but their \"leader\" Hanno the Great was one of the most influential personalities in Carthage during the war. The name of the cult derives from that of the goddess Anat, a deity of the Phoenician pantheon, goddess of fertility.",
      "tablo_eng11" => "Cannae - Events in the year 216 BC. This battle is one of the greatest Roman defeats and in general is historically well represented, especially in the \"strategic\" phase at the beginning of it. The sacrifice of Aemilius Paulus is also represented, replacing Gnaeus Lentulus with Publius, who stars in the episode of the harangues before those who wanted to flee, which is true according to what the Greek Polybius tells us.",
      "tablo_eng12" => "Pantheon. In the pantheon, a secondary quest focuses on various momments of Roman history, these are generally quite historical, and their cities have also been made based on their real plan. The plots of Augustus and Belisarius are less accurated, on the contrary, the chapter of Aeneas follows Virgil's work quite literally.",
      "tablo_eng13" => "Baecula - Events in the year 209 BC. The battle of Baecula is represented quite correctly by the display on a hill that must be climbed, the Roman army had to assault the Carthaginians who were at the top of it. Obviously the intervention of Olympeus is invented, and in reality Hasdrubal escaped on his own to return with his brother, but he would die in the battle of Metaurus.",
      "tablo_eng14" => "Olympus. Olympus is a divine place in Roman mythology, it resembles the Greek one, and within the game we find most of the gods of the Latin pantheon, highlighting Janus and the representation of Zeus as opposed to Jupiter. The appearance of Olympus is also reminiscent of what the Elysian fields might have looked like and contrasts with the underworld, where we find Dante.",
      "tablo_eng15" => "Zama - Events in the year 202 BC. The representation of the battle is, especially in its first phase, very accurated. The death of Cepressus by Anaid is something made up for the plot and the duel between Scipio and Hannibal possibly did not occur, however it is reflected that after winning this battle and conquering Africa Publius began to be called Scipio Africanus, or, in latin: \"Scipio Africanvs\".",
      "tablo_eng16" => "Atlantis. Atlantis, mentioned in Plato's myth, is a famous part of the classical mythology. In this city we find Alexander the Great, a Macedonian hero from the 4th century BC, which marked the history of the ancient world, being exalted and converted into a true legend. His survival is obviously false and the existence of Atlantis has not been proven... yet..."
    }

    # Speaks the transcription of the table the screen just slid in, or the generic fullscreen-image
    # notice for a picture this table does not know; either way the text is stashed for the info key so
    # a long page can be re-read.
    def self.on_show(scene, select)
      pics = PokeAccess.ivar(scene, :@pictures)
      base = (pics.is_a?(Array) && pics[select.to_i]) ? pics[select.to_i].to_s.split("/").last : nil
      t = base ? TEXTS[base] : nil
      if t
        PokeAccess.speak_clean(t, true)
        PokeAccess::Info.set_info(:text, PokeAccess.clean(t))
      else
        PokeAccess.speak(PokeAccess::I18n.t(:img_fullscreen), true)
      end
    rescue StandardError
      nil
    end
  end
end

PokeAccess::Game.define("africanus") do
  before("TablesScreen", :showImage, :optional => true) do |scene, args|
    PokeAccess::AfricanusTablas.on_show(scene, args[0])
  end
end
