# The fusion chooser (DoublePreviewScreen, whose hooks also cover FusionPreviewScreen): the two possible fusions,
# which the screen never names, or cancel (@selected -1).
module PokeAccess
  module IFFusionPreview
    # The base a fusion id is packed with (head * nb + body), read from the game (Hoenn reassigns it to 576).
    # The leading :: is needed: a bare Settings here is PokeAccess::Settings.
    def self.nb
      (::Settings::NB_POKEMON rescue 501)
    end

    # True only for a species entry, not the Pokemon objects the same ivars may hold.
    def self.species?(v)
      return false if v.nil?
      return false if defined?(::Pokemon) && v.is_a?(::Pokemon)
      return true if defined?(GameData::Species) && v.is_a?(GameData::Species)
      v.respond_to?(:head_pokemon)
    rescue StandardError
      false
    end

    # The fused species on one side, or nil. side 0 = left (poke1 head), 1 = right (the reverse).
    def self.side_species(scene, side)
      direct = PokeAccess.ivar(scene, side == 0 ? :@species_left : :@species_right)
      return direct if species?(direct)
      p1 = PokeAccess.ivar(scene, :@poke1)
      p2 = PokeAccess.ivar(scene, :@poke2)
      return nil unless p1 && p2
      a = (p1.species_data.id_number rescue nil)
      b = (p2.species_data.id_number rescue nil)
      return nil if a.nil? || b.nil?
      base = nb
      id = (side == 0) ? (a * base + b) : (b * base + a)
      (GameData::Species.get(id) rescue nil)
    rescue StandardError
      nil
    end

    # A fusion as spoken: its name plus which Pokemon gives the head and which the body. With the screen, at the
    # Pokemon choice reading's level: from medium the types it draws under the sprite and whether the Pokedex has
    # not seen it (its tinted sprite), at full what the tint's colour tells and the level it draws.
    # param side the screen's side (0 left, 1 right) the fusion is drawn on, for its tint
    def self.describe(sp, scene = nil, side = nil)
      return nil if sp.nil?
      name = (sp.name rescue nil)
      head = (sp.head_pokemon.name rescue nil)
      body = (sp.body_pokemon.name rescue nil)
      return nil if name.nil? && head.nil? && body.nil?
      base = if head && body
               PokeAccess::I18n.t(:if_fusion_side, :name => (name || "#{head} #{body}"), :head => head, :body => body)
             else
               name.to_s
             end
      return base if scene.nil?
      parts = [[base, :brief]]
      parts.push([types_text(sp), :medium]) if PokeAccess.ivar(scene, :@draw_types)
      parts.push([PokeAccess::I18n.t(:if_fusion_unseen), :medium]) if unseen?(sp)
      parts.push([tint(scene, sp, side), :full])
      level = PokeAccess.ivar(scene, :@access_if_level)
      parts.push([PokeAccess::I18n.t(:if_fusion_level, :n => level), :full]) if level
      PokeAccess::Verbosity.line(:pokemon_choice, parts)
    rescue StandardError
      nil
    end

    # The fusion's types as drawPokemonType shows them: one when both are the same.
    def self.types_text(sp)
      types = [(sp.type1 rescue nil), (sp.type2 rescue nil)].compact.uniq
      names = types.map { |t| (GameData::Type.get(t).name rescue t.to_s) }
      names.empty? ? nil : PokeAccess::I18n.t(:pdx_type, :t => names.join(" "))
    end

    # Whether the Pokedex has not seen a fusion, which draw_window tints; a game that cannot tell says nothing.
    def self.unseen?(sp)
      !$Trainer.seen?(sp.id_number)
    rescue StandardError
      false
    end

    # What the colour draw_window tints an unseen fusion's sprite with tells, by the game's own tests: blue, a custom
    # sprite already on disk; green, a custom one not downloaded yet; white, an autogenerated one. nil for a seen
    # fusion, or where the game cannot tell.
    def self.tint(scene, sp, side)
      return nil unless side && unseen?(sp)
      pif = PokeAccess.ivar(scene, side == 0 ? :@sprite_left : :@sprite_right)
      return PokeAccess::I18n.t(:if_sprite_local) if (pif.local_path rescue nil)
      PokeAccess::I18n.t(customSpriteExistsSpecies(sp.id_number) ? :if_sprite_custom : :if_sprite_auto)
    rescue StandardError
      nil
    end

    # Keeps the level drawFusionInformation paints ("Lv. N", the same on both sides) where the screen draws one.
    def self.note_level(scene, level)
      scene.instance_variable_set(:@access_if_level, level) if PokeAccess.ivar(scene, :@draw_level) && level
    rescue StandardError
      nil
    end

    # Voices the focused option once per change: the two fusions, or the cancel button.
    def self.focus(scene)
      sel = PokeAccess.ivar(scene, :@selected)
      return if sel.nil?
      PokeAccess::Cursor.announce(scene, :if_fusion, sel, true) do
        if sel.to_i < 0
          PokeAccess::I18n.t(:if_fusion_cancel)
        else
          d = describe(side_species(scene, sel.to_i), scene, sel.to_i)
          d || (PokeAccess.ivar(scene, :@poke1) ? PokeAccess::I18n.t(:if_fusion_unknown) : nil)
        end
      end
    rescue StandardError
      nil
    end
  end
end

PokeAccess::Game.define("infinitefusion_common") do
  before("DoublePreviewScreen", :drawFusionInformation, :optional => true) do |s, args|
    PokeAccess::IFFusionPreview.note_level(s, args[1])
  end
  before("DoublePreviewScreen", :startSelection) { |s, _a| PokeAccess::IFFusionPreview.focus(s) }
  after("DoublePreviewScreen", :updateSelectionGraphics) { |s, _r, _a| PokeAccess::IFFusionPreview.focus(s) }
end

PokeAccess::Verbosity.define_reading(:pokemon_choice, :vb_pokemon_choice, :vbh_pokemon_choice)
